[2022-11-11T10:57:01.213+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-10T00:00:00+00:00 [queued]>
[2022-11-11T10:57:01.242+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-10T00:00:00+00:00 [queued]>
[2022-11-11T10:57:01.244+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-11T10:57:01.245+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-11T10:57:01.247+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-11T10:57:01.280+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-10 00:00:00+00:00
[2022-11-11T10:57:01.292+0000] {standard_task_runner.py:55} INFO - Started process 239 to run task
[2022-11-11T10:57:01.302+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-11-10T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpkavdk2qx']
[2022-11-11T10:57:01.311+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask create_table
[2022-11-11T10:57:01.512+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-11-10T00:00:00+00:00 [running]> on host bca668ad4dbc
[2022-11-11T10:57:01.701+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-10T00:00:00+00:00
[2022-11-11T10:57:01.734+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2022-11-11T10:57:01.745+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-11-11T10:57:01.749+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2022-11-11T10:57:01.777+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221110T000000, start_date=20221111T105701, end_date=20221111T105701
[2022-11-11T10:57:01.837+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-11T10:57:01.914+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
