[2022-11-09 08:35:10,703] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2022-11-09 08:35:10,866] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2022-11-09 08:35:10,869] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-09 08:35:10,882] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-09 08:35:10,886] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-09 08:35:11,217] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-11-08 00:00:00+00:00
[2022-11-09 08:35:11,284] {standard_task_runner.py:52} INFO - Started process 7430 to run task
[2022-11-09 08:35:11,350] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2022-11-08T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpdx8m68_h', '--error-file', '/tmp/tmpgy83x7bf']
[2022-11-09 08:35:11,367] {standard_task_runner.py:80} INFO - Job 12: Subtask store_user
[2022-11-09 08:35:12,257] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user scheduled__2022-11-08T00:00:00+00:00 [running]> on host ce8aab517b0f
[2022-11-09 08:35:13,238] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-11-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-08T00:00:00+00:00
[2022-11-09 08:35:13,258] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-11-09 08:35:13,456] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-11-09 08:35:13,590] {python.py:173} INFO - Done. Returned value was: None
[2022-11-09 08:35:13,739] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20221108T000000, start_date=20221109T083510, end_date=20221109T083513
[2022-11-09 08:35:14,001] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-09 08:35:14,690] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
